#!/bin/bash

echo "Select the instance to exec bash"

container=$(docker-compose ps | awk '/Up/ {print $1}' | fzf --reverse --height 50%  --bind 'enter:execute(echo {})+abort')

# echo "$container"

if [ -z "$container" ];
then
    echo "No container selected"
else
    docker exec -ti $container bash
fi

